[package]
name = "obscura-app"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
description            = "Obscura desktop application."
publish                = false

[lib]
name       = "obscura_app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "obscura-app"
path = "src/main.rs"

[lints]
workspace = true

[build-dependencies]
tauri-build      = { workspace = true }

[dependencies]
obscura-crypto   = { workspace = true }
obscura-vault    = { workspace = true }
obscura-platform = { workspace = true }
obscura-webauthn = { workspace = true }
tauri            = { workspace = true }
tauri-plugin-dialog = { workspace = true }
arboard          = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
uuid             = { workspace = true }
time             = { workspace = true }
zeroize          = { workspace = true }
subtle           = { workspace = true }
