[package]
name = "obscura-vault"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
description            = "Vault data model and storage format for Obscura."

[lints]
workspace = true

[dependencies]
obscura-crypto = { workspace = true }
serde          = { workspace = true }
uuid           = { workspace = true }
time           = { workspace = true }
zeroize        = { workspace = true }
subtle         = { workspace = true }
hmac           = { workspace = true }
sha1           = { workspace = true }
sha2           = { workspace = true }
rand_core      = { workspace = true }
thiserror      = { workspace = true }
ciborium       = { workspace = true }

[dev-dependencies]
uuid           = { workspace = true }
