[package]
name = "obscura-platform"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[lints]
workspace = true

[dependencies]
obscura-crypto = { workspace = true }
thiserror      = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Foundation",
    "Security_Credentials",
    "Security_Cryptography",
    "Storage_Streams",
] }
